// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EQ2PGx9tNtCILu9aSimSTr9SQ5l2OFU',
    appId: '1:666683213874:web:f27803c3a8a296dcb0542b',
    messagingSenderId: '666683213874',
    projectId: 'projetoflutter-bc449',
    authDomain: 'projetoflutter-bc449.firebaseapp.com',
    storageBucket: 'projetoflutter-bc449.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLlpY7tdJJm_wCMWmVpURfHzkOfCng-ZQ',
    appId: '1:666683213874:android:84ddcfd065f1b0a3b0542b',
    messagingSenderId: '666683213874',
    projectId: 'projetoflutter-bc449',
    storageBucket: 'projetoflutter-bc449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiqIahCmY1C89ZaSbihpiTkvcfyMntbsQ',
    appId: '1:666683213874:ios:879226b8fa3b5b11b0542b',
    messagingSenderId: '666683213874',
    projectId: 'projetoflutter-bc449',
    storageBucket: 'projetoflutter-bc449.firebasestorage.app',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiqIahCmY1C89ZaSbihpiTkvcfyMntbsQ',
    appId: '1:666683213874:ios:879226b8fa3b5b11b0542b',
    messagingSenderId: '666683213874',
    projectId: 'projetoflutter-bc449',
    storageBucket: 'projetoflutter-bc449.firebasestorage.app',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EQ2PGx9tNtCILu9aSimSTr9SQ5l2OFU',
    appId: '1:666683213874:web:5fe251a9a4888a44b0542b',
    messagingSenderId: '666683213874',
    projectId: 'projetoflutter-bc449',
    authDomain: 'projetoflutter-bc449.firebaseapp.com',
    storageBucket: 'projetoflutter-bc449.firebasestorage.app',
  );
}
